"""
Konfigürasyon Ayarları
"""
import os

# Sistem Optimizasyonları
os.environ['OMP_NUM_THREADS'] = '1'
os.environ['OPENBLAS_NUM_THREADS'] = '1'
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

# SPEED CONFIG
SPEED_CONFIG = {
    'FRAME_SKIP': 1,
    'TARGET_FPS': 15,
    'DISPLAY_WIDTH': 640,
    'DISPLAY_HEIGHT': 480,
    'PROCESS_WIDTH': 1920,
    'PROCESS_HEIGHT': 1080,
    'USE_HALF_PRECISION': True,
    'BATCH_SIZE': 2,
    'PARALLEL_PROCESSING': True,
    'THREAD_WORKERS': 12,
    'MIN_DETECTION_CONFIDENCE': 0.3,
    'SKIP_SMALL_CARS': False,
    'MIN_CAR_SIZE': 200,
    'MAX_CARS_PER_FRAME': 3,
    'MAX_PLATES_PER_CAR': 2,
    
    # 300 DPI AYARLARI
    'ENABLE_300DPI': True,
    'DPI_OUTPUT_SIZE': (1200, 400),
    
    # STITCHING AYARLARI
    'STITCHING_ENABLED': True,
    'STITCHING_WINDOW': 10,
    'STITCHING_MIN_OBSERVATIONS': 3,
    'STITCHING_MAJORITY_RATIO': 0.6,
    'STITCHING_CONFIDENCE_BOOST': 1.2,
    'STITCHING_SIMILARITY_THRESHOLD': 0.85,
    
    # TEKRAR ENGELLEME
    'DUPLICATE_CHECK_ENABLED': True,
    'DUPLICATE_TIME_WINDOW': 30,
    'DUPLICATE_PRIMARY_THRESHOLD': 0.95,
    'DUPLICATE_SECONDARY_THRESHOLD': 0.85,
    'DUPLICATE_STRICT_MODE': False,
    
    # OCR AYARLARI
    'OCR_WORKERS': 2,
    'PLATE_COOLDOWN': 2,
    
    # BOUNDING BOX PADDING
    'BBOX_PADDING': 15,
    
    # RESIZE FAKTÖRÜ
    'OCR_RESIZE_FACTOR': 1.0,
    
    # KONTRAST AYARLARI
    'CLAHE_CLIP_LIMIT': 3.0,
    'CLAHE_GRID_SIZE': (8, 8),
    
    # TEMPORAL VOTING
    'TEMPORAL_VOTING_WINDOW': 7,
    'TEMPORAL_VOTING_MIN_VOTES': 4,
}